[package]
name = "sunray"
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0-only"
description = "feature-rich hardware ray-tracing library"
repository = "https://github.com/Kalsifer-742/sunray.git"
readme = "README.md"
keywords = ["gamedev", "graphics"]
categories = ["graphics", "hardware-support", "game-development"]

[dependencies]
ash = {  version = "0.38", features = ["linked"] }
ash-window = "0.13"
winit = { version = "0.29", features = ["rwh_06"] }

# for compile-time shader compilation to spirv
glsl-to-spirv-macros = "0.1.1"
glsl-to-spirv-macros-impl = "0.1.0"
